### ISSUE TITLE
working dir dependence of `git describe`

### ISSUE THREAD

**Issue by wsdewitt** [carjed/helmsman#11]
This method of getting the version fails if one is calling `helmsman.py` from another working directory (e.g. if it's a submodule).

https://github.com/carjed/helmsman/blob/2ab6f7b1af9fa3b6464ad812c3f7ee67dd81f5b0/helmsman.py#L29-L30

Also here:
https://github.com/carjed/helmsman/blob/2ab6f7b1af9fa3b6464ad812c3f7ee67dd81f5b0/helmsman.py#L280-L281

**Comment by mortunco** [comment]
i am having the same problem.
