### ISSUE TITLE
maxac default inconsistent with docs

### ISSUE THREAD

**Issue by wsdewitt** [carjed/helmsman#13]
According to [usage.md](https://github.com/carjed/helmsman/blob/master/docs/usage.md#specify-maximum-allele-count-of-snvs-to-analyze) the default for option `--maxac` is `1` (singletons only)

> ### Specify maximum allele count of SNVs to analyze
> 
> `--maxac [INT]`
> 
> By default, *Helmsman* will evaluate only singleton SNVs (`--maxac 1`). To include more common SNVs, increase the value of this parameter. To include all SNVs, use `--maxac 0`. This is not recommended when using *Helmsman* for QC functionality, but may be useful for more general mutation signature analysis.
> 

But the code seems to default to `0` (all SNVs).
https://github.com/carjed/helmsman/blob/2ab6f7b1af9fa3b6464ad812c3f7ee67dd81f5b0/helmsman.py#L164-L172

**Comment by carjed** [comment]
Looks like this was carried over when I implemented code from [carjed/doomsayer](http://github.com/carjed/doomsayer). Will update documentation in next release.
