### ISSUE TITLE
pip_reqs.txt errors

### ISSUE THREAD

**Issue by arundurvasula** [carjed/helmsman#7]
Looks like there are some duplicate entries and syntax errors in the pip_reqs.txt:

Doubles: matplotlib, pyfaidx, joblib
Syntax errors (`=` should be `==`): 

    cyvcf2=0.8
    pyfaidx=0.5
    joblib=0.11

**Comment by carjed** [comment]
thanks for catching this--must have copied and pasted these requirements from `env.yml` at some point
