### ISSUE TITLE
Can helmsman identify optimal number of mutational signatures? (Rank in helmsman)

### ISSUE THREAD

**Issue by gguy1048** [carjed/helmsman#8]
Can helmsman identify optimal number of mutational signatures? (Rank in helmsman)

**Comment by carjed** [comment]
I have this partially implemented—if you set `--rank 0` (or just exclude the `--rank` option altogether), it will iteratively run with rank K=2,3,4,... and calculate the explained variance for each rank, stopping at rank K if the explained variance for rank (K+1) fails to increase by more than 0.001.

The only catch is that it's currently set to go no higher than K=6, so I'll add a fix to allow higher ranks to be assessed.
