### ISSUE TITLE
Example vcf input file

### ISSUE THREAD

**Issue by jadeshi** [carjed/helmsman#9]
EDIT: never mind, just realized that the data folder has an example of one.

**Comment by carjed** [comment]
Great, hopefully that helps—seems that the issue with https://cancer.sanger.ac.uk/cosmic/file_download/GRCh38/cosmic/v87/VCF/CosmicCodingMuts.vcf.gz is that it is a "sites only" VCF file and does not include individual genotypes. Helmsman requires input data to indicate which sample(s) each variant occurs in.
